services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/config
      - "/home/multiplaie/Musique:/media/music"
      - "/home/multiplaie/Vidéos/Films:/media/films"
      - "/home/multiplaie/Vidéos/Séries:/media/series"
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=http://192.168.1.160:8096
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"     # interface web de gestion
      - "443:443"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt